# Generated by Django 5.1.1 on 2025-02-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_category_rename_date_added_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=None),
        ),
    ]
