# Generated by Django 5.1.1 on 2025-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_user_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
