# Generated by Django 5.1.1 on 2025-02-26 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_recipe_liked_by_recipe_likes_alter_recipe_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='likes',
            new_name='saves',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
