# Generated by Django 5.1.1 on 2025-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_likes_recipe_saves_remove_recipe_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Rating from 0.0 to 5.0', max_digits=2),
        ),
        migrations.AlterField(
            model_name='reciperatingsandreviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Rating from 0.0 to 5.0', max_digits=2),
        ),
    ]
